### ISSUE TITLE
Why not just a one-liner?

### ISSUE THREAD

**Issue by mapio** [netham91/Quick-Share#2]
What is the advantage of this with respect to

```
python -m SimpleHTTPServer $PORT
```

if you think you cant' remember it, why not just a shell alias?

**Comment by netham91** [comment]
Sure, there is no big advantage. This is actually a starting point to widget I want to make. It's a building block. I plan to add some options. Apart from that, it displays ip for now which is helpful for some. I did add a alias too : quickshare.

**Comment by mapio** [comment]
I see.
